services:
  - type: web
    name: zagadochnik
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_SECRET
        generateValue: true
